email_contact: vuongphan139.it@gmail.com
copyright: © 2019 Nam Vuong Story
max_length_name: 50
max_length_account_name: 50
max_length_email: 255
min_length_password: 6
resize_image_limit: [300, 300]
stories_per_page: 15
progress_done: 1
text_area_rows_chapter_content: 8
text_area_rows_story_description: 6
chapters_newest_limit: 12
stories_newest: 6
stories_manager_page: 12
categories_per_page: 5
size_comment: 140
size_gravatar: 50
comment_items_page: 5
gravatar_size_user: 50
story_progress_done: 1
